controllers:
    resource: ../../src/Controller/
    type: annotation
src:
    resource: ../../src/Acme/TestBundle/Controller/
    type: annotation
kernel:
    resource: ../../src/Kernel.php
    type: annotation
