controllers:
    resource: ../../src/Controller/
    type: annotation
src:
    resource: ../../src/Gagan/Workflow/Controller/
    type: annotation
kernel:
    resource: ../../src/Kernel.php
    type: annotation
